In [ ]:
#1

In [5]:
import cv2
import numpy as np

img = cv2.imread('images/dave.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) 
edges = cv2.Canny(gray,50,150,apertureSize = 3)
lines = cv2.HoughLines(edges,1,np.pi/180,200)
print(lines)
for rho,theta in lines[8]:
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*rho
    y0 = b*rho
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))

    cv2.line(img,(x1,y1),(x2,y2),(0,0,255),2)

cv2.imshow('houghlines3.jpg',img)
cv2.waitKey(0) 
cv2.destroyAllWindows() 

[[[ 2.7100000e+02  1.5707964e+00]]

 [[ 2.6800000e+02  1.5707964e+00]]

 [[ 2.2600000e+02  0.0000000e+00]]

 [[ 1.9500000e+02  1.7453292e-02]]

 [[ 1.6200000e+02  3.4906585e-02]]

 [[ 1.5900000e+02  3.4906585e-02]]

 [[-2.6200000e+02  3.1241393e+00]]

 [[-2.9300000e+02  3.1066861e+00]]

 [[ 1.9300000e+02  1.7453292e-02]]

 [[ 2.2800000e+02  0.0000000e+00]]

 [[ 1.6200000e+02  1.5707964e+00]]

 [[ 6.2000000e+01  8.7266460e-02]]

 [[-2.9500000e+02  3.1066861e+00]]

 [[ 5.9000000e+01  8.7266460e-02]]

 [[-2.5900000e+02  3.1241393e+00]]

 [[ 1.5900000e+02  1.5707964e+00]]

 [[ 3.4800000e+02  1.5707964e+00]]

 [[-3.7800000e+02  3.0717795e+00]]

 [[-3.2700000e+02  3.0892327e+00]]

 [[ 6.4000000e+01  1.0471976e-01]]]


In [ ]:
#2

In [8]:
import cv2
import numpy as np
import sys

def onTrackbarChange(max_slider):
    global img
    global dst
    global gray

    dst = np.copy(img)

    th1 = max_slider 
    th2 = th1 * 0.4
    edges = cv2.Canny(img, th1, th2)
    
    #Aplicar la transformada probabilística de hough para detectar líneas
    lines = cv2.HoughLinesP(edges, 2, np.pi/180.0, 50, minLineLength=10, maxLineGap=100)

    #--dibujar líneas sobre los puntos detectados
    for line in lines:
        x1, y1, x2, y2 = line[0]
        cv2.line(dst, (x1, y1), (x2, y2), (0,0,255), 1)

    cv2.imshow("Imagen Resultante", dst)    
    cv2.imshow("Edges",edges)

if __name__ == "__main__":
    
    #--Leer la imagen
    img = cv2.imread('images/lanes.jpg')
    
    #--Crear una copia para su posterior uso
    dst = np.copy(img)

    #--Convertir a gris
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Crear las ventanas
    cv2.namedWindow("Edges")
    cv2.namedWindow("Imagen Resultante")
      

    # Inicializar el valor del umbral
    initThresh = 500

    # Maximo valor del umbral
    maxThresh = 1000

    cv2.createTrackbar("threshold", "Imagen Resultante", initThresh, maxThresh, onTrackbarChange)
    onTrackbarChange(initThresh)

    while True:
        key = cv2.waitKey(1)
        if key == 27:
            break

    cv2.destroyAllWindows()

In [ ]:
#3

In [9]:
import cv2
import numpy as np
import sys

def onTrackbarChange(max_slider):
    cimg = np.copy(img)

    p1 = max_slider
    p2 = max_slider * 0.4

    #--Detectar circulos usando la transformada de Hough para detectar círculos
    circles = cv2.HoughCircles(gray, cv2.HOUGH_GRADIENT, 1, cimg.shape[0]/64, param1=p1, param2=p2, minRadius=25, maxRadius=50)

    #--Si por lo menos se ha detectado un círculo
    if circles is not None:
        cir_len = circles.shape[1] # almacenar la longitud de los círculos encontrados
        circles = np.uint16(np.around(circles))
        for i in circles[0, :]:
            # Dibuja el círculo exterior
            cv2.circle(cimg, (i[0], i[1]), i[2], (0, 255, 0), 2)
            # Dibuja el centro del círculo
            cv2.circle(cimg, (i[0], i[1]), 2, (0, 0, 255), 3)
    else:
        cir_len = 0 # no se detectaron círculos
    
    # Mostrar imagen de salida
    cv2.imshow('Image', cimg)    

    # Imagen de borde para depuración
    edges = cv2.Canny(gray, p1, p2)
    cv2.imshow('Edges', edges)
   
if __name__ == "__main__":
    # Leer imagen
    img = cv2.imread("images/brown-eyes.jpg", 1)

    # Convertir a escala de grises
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Crear ventanas de visualización
    cv2.namedWindow("Edges")
    cv2.namedWindow("Image")
        # La barra de seguimiento se utilizará para cambiar el umbral del borde
    initThresh = 105 
    maxThresh = 200 

    # Crear barra de seguimiento
    cv2.createTrackbar("Threshold", "Image", initThresh, maxThresh, onTrackbarChange)
    onTrackbarChange(initThresh)
    
    while True:
        key = cv2.waitKey(1)
        if key == 27:
            break
    cv2.destroyAllWindows()
