In [ ]:
# 1. Eliminar las líneas más delgadas de la figura (a) y obtener la figura (b) aplicando
#filtrado. Indicar qué tipo de filtro ha utilizado.
#Fig1_a.jpg

In [12]:
import cv2 as cv
#leyendo la imagen cuyo ruido se eliminará usando la función imread()
imageread = cv.imread('images/Fig1_a.jpg')
#usando la función medianBlur() para eliminar el ruido de la imagen dada
imagenormal = cv.medianBlur(imageread, 3)
#mostrando la imagen sin ruido como la salida en la pantalla
cv.imshow('original:', imageread)
cv.imshow('imagen con ruido disminuido',imagenormal)
cv.waitKey(0)
cv.destroyAllWindows()
#Se utiliza un suavizada utilizando la mediana de los pixeles
#medianBlur

In [7]:
# 2.
fig1.png

In [26]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
#--leer la imagen
img= cv2.imread('images/fig1.png', 0)
cv2.imshow('Imagen original', img)

#--aplicando la ecualización
histequ = cv2.equalizeHist(img)
#--muestra la imagen ecualizada
cv2.imshow('Imagen ecualizada', histequ)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
#3.
#Se escala por un factor de 2 con el método de interpolación del vecino más cercano.
#Escriba un programa Python para realizar lo indicado y muestre la matriz final

In [24]:
import cv2
import numpy as np
#--leer imagen
image = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
])
#--obtener dimensiones
ancho = image.shape[1] #columnas
alto = image.shape[0] # filas
print(alto,ancho)
#--escalando la imagen 
imageOut = cv2.resize(image,(2*ancho,2*alto), interpolation=cv2.INTER_NEAREST)
#--mostrar las imágenes
print("Matriz original: ")
print(image)
print("Matriz Escalada: ")
print(imageOut)

3 3
Matriz original: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Matriz Escalada: 
[[0 0 1 1 2 2]
 [0 0 1 1 2 2]
 [3 3 4 4 5 5]
 [3 3 4 4 5 5]
 [6 6 7 7 8 8]
 [6 6 7 7 8 8]]
